Re-added mistakenly removed multitimerthread.h/.icc files.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/socketapi@2653 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/make-symbols b/make-symbols
--- a/make-symbols
+++ b/make-symbols
@@ -2,7 +2,7 @@
 # $Id$
 #
 # Debian Packaging Scripts
-# Copyright (C) 2002-2011 by Thomas Dreibholz
+# Copyright (C) 2002-2012 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -28,24 +28,35 @@ echo ""
 echo "Creating binary package ..."
 echo ""
 
-./bootstrap && debuild -b -us -uc || exit 1
+./bootstrap && debuild -i -us -uc -b || exit 1
 
 
 for LIBRARY_PACKAGE in $LIBRARY_PACKAGES ; do
    echo ""
-   echo "Creating symbols for library package $LIBRARY_PACKAGE ..."
+   echo "###### Creating symbols for library package $LIBRARY_PACKAGE ... ######"
    echo ""
 
    # Symbol file generation according How-To at:
    # http://swik.net/Ubuntu/Planet+Ubuntu/Dmitrijs+Ledkovs%3A+Lintian+no-symbols-control-file/d4q9h
 
+   find . -maxdepth 1 -name "$LIBRARY_PACKAGE.new_symbol_file" | xargs --no-run-if-empty rm -f
    find . -maxdepth 1 -name "dpkg-gensymbols*" | xargs --no-run-if-empty rm -f
+   find . -maxdepth 1 -name "symbols-*.patch" | xargs --no-run-if-empty rm -f
 
-   echo "dpkg-gensymbols -p$LIBRARY_PACKAGE -Pdebian/$LIBRARY_PACKAGE | patch -p0"
-   dpkg-gensymbols -p$LIBRARY_PACKAGE -Pdebian/$LIBRARY_PACKAGE | patch -p0 || exit 1
+   echo "--> dpkg-gensymbols -p$LIBRARY_PACKAGE -Pdebian/$LIBRARY_PACKAGE"
+   touch debian/$LIBRARY_PACKAGE.symbols
+   dpkg-gensymbols -p$LIBRARY_PACKAGE -Pdebian/$LIBRARY_PACKAGE >symbols-$LIBRARY_PACKAGE.patch
+
+   echo "--> patch -p0 --output=$LIBRARY_PACKAGE.new_symbol_file <symbols-$LIBRARY_PACKAGE.patch"
+   patch -p0 --output=$LIBRARY_PACKAGE.new_symbol_file <symbols-$LIBRARY_PACKAGE.patch
 
    # Replace C++ symbols which are different on 32- and 64-bit systems
-   ./replace-cpp-symbols <dpkg-gensymbols* >debian/$LIBRARY_PACKAGE.symbols || exit 1
+   if [ -e "$LIBRARY_PACKAGE.new_symbol_file" ] ; then
+      echo "--> ./replace-cpp-symbols <$LIBRARY_PACKAGE.new_symbol_file >debian/$LIBRARY_PACKAGE.symbols"
+      ./replace-cpp-symbols <$LIBRARY_PACKAGE.new_symbol_file >debian/$LIBRARY_PACKAGE.symbols || exit 1
+   else
+      echo "ERROR: patch has not created output file $LIBRARY_PACKAGE.new_symbol_file!"
+   fi
 
    # Strip off ubuntu version!
    perl -pi -e 's/-\d.*//' debian/$LIBRARY_PACKAGE.symbols || exit 1
